### ISSUE TITLE
How to structure the data when applying the framework to my own dataset?

### ISSUE THREAD

**Issue by marcellosicbaldi** [menouarazib/eventdetector#2]
Hi! First of all thanks for making this open-source. I would like to apply the framework to physiological time series data. However, it is not that clear to me how to structure the `dataset` and the `events`. I saw that in the two examples you provide, the `events` are a `DataFrame` containing a single timestamp. Is that because the duration of each event is the same? Can the package generalize to events of variable duration (e.g., 2-4 seconds)?

**Comment by menouarazib** [comment]
Hi! Thank you for your interest in this open-source package. Indeed, you can pass the events as a `DataFrame` or a `list`. Each event can be defined as a single time point or an interval of time (starting time and stopping time).
For instance, if events are given as a `DataFrame`, it can either have two columns where one column contains the starting time of each event and the second column contains the stopping time. Alternatively, it can just contain one column with the midpoint of each event.
In your case, you can pass the events as a `DataFrame` with two columns containing the starting and stopping time of each event. Please don't hesitate to ask if you have any further questions. I'm here to help! 😊

**Comment by marcellosicbaldi** [comment]
Thank you for the clear reply. I am still having some issues (each time point gets predicted as an event), I think that I might be missing something about the parameters. 
The main difference of my data from yours (credit card and Mars) is that I have a sampling time of 10 ms, and the events last from 2 to 4 seconds. Should I make some major changes to the default parameters? I hope that I am not asking too much 😅. Thank you in advance 🙏

**Comment by menouarazib** [comment]
You're welcome, I'm happy to help! Our method, provided in this package, divides the time series into overlapping partitions, known as sliding windows. The `width` argument determines the width of each window, which is an integer representing the number of time steps in each window. Additionally, the `step` argument defines the number of time steps to slide each window.
In your case, with a sampling time of 10 ms, you might want to set `width` to 401. This would make the duration of each window match the maximum duration of your events: (401-1)*10 ms = 4000 ms = 4 seconds.
For instance, the code below specifies the width of the windows to be 401, corresponding to a 4-second duration. Your events will be considered to have a maximum 4-second duration.

```
meta_model = MetaModel(output_dir="your_output_folder", dataset=your_dataset, events=your_events, width=401, step=1)
meta_model.fit()

```
Please don't hesitate to ask if you have any further questions. I'm here to help! 😊

**Comment by marcellosicbaldi** [comment]
This was super useful and the detection results improved a lot 🚀 . So, if I got it correctly, with this line of code 
`interval = Interval(mid_time - radius, mid_time + radius)`
you define new events that are centered around the middle of each event and with duration equal to `width`. Therefore, if I set `width` to 401, each event will be considered lasting 4 seconds (even shorter and longer ones). So there is no way to predict events of variable duration, right? Or am I missing something?

**Comment by menouarazib** [comment]
I'm delighted to hear that the results have been improved. Yes, your understanding is accurate. Currently, the package can predict the midpoint of each event with a duration equal to `width`. As a future feature, we will strive to predict events with varying durations. As an interim solution, the `width` could be set to the average duration of the events?
